#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom broom tidy
#' @importFrom cowplot get_legend
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr full_join
#' @importFrom dplyr glimpse
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr rename_all
#' @importFrom dplyr rename_with
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom dplyr vars
#' @importFrom gtsummary add_overall
#' @importFrom gtsummary add_p
#' @importFrom gtsummary all_categorical
#' @importFrom gtsummary all_continuous
#' @importFrom gtsummary all_stat_cols
#' @importFrom gtsummary as_flex_table
#' @importFrom gtsummary bold_labels
#' @importFrom gtsummary modify_caption
#' @importFrom gtsummary modify_header
#' @importFrom gtsummary tbl_likert
#' @importFrom gtsummary tbl_merge
#' @importFrom gtsummary tbl_svysummary
#' @importFrom haven as_factor
#' @importFrom haven read_dta
#' @importFrom haven write_dta
#' @importFrom magrittr %>%
#' @importFrom mice complete
#' @importFrom mice mice
#' @importFrom psych fa
#' @importFrom psych fa.parallel
#' @importFrom psych factor.scores
#' @importFrom psych KMO
#' @importFrom purrr reduce
#' @importFrom rlang sym
#' @importFrom stargazer stargazer
#' @importFrom survey svydesign
#' @importFrom tidyr pivot_wider
## usethis namespace: end
NULL
